apiVersion: v1
kind: Service
metadata:
    name: helloworldphp-clusterip
spec:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
    selector:
        app: helloworldphp-app
        type: helloworldphp-type

