apiVersion: v1
kind: Pod
metadata:
    name: helloworldphp-pod
    labels:
        app: helloworldphp-app
        type: helloworldphp-type
spec:
    containers:
      - name: helloworldphp-container
        image: helloworldphpimage:latest
        imagePullPolicy: Never

